version: "3"
services:
  nginx:
    container_name: nginx
    ports:
      - "8080:80"
    build:
      context: ./nginx
    depends_on:
      - node-app

  node-app:
    container_name: node_app
    # environment:
    #   - PORT=3000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  mongo-db:
  redis_data: