version: "3"
services:
  nginx:
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/web-root:/usr/share/nginx/html/
  node-app:
    build:
      context: ./API
      args:
        NODE_ENV: development
    volumes:
      - ./API:/app
      - /app/node_modules
      # - /app/uploads
    environment:
      - NODE_ENV=development
      - MONGO_USER=testUser
      - MONGO_PASSWORD=mongoPassword

    command: npm run devv
  mongo:
    environment:
      # this is just for dev purpose
      - MONGO_INITDB_ROOT_USERNAME=testUser
      - MONGO_INITDB_ROOT_PASSWORD=mongoPassword
