version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      # - ./nginx:/etc/nginx/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    container_name: node_app
    environment:
      - PORT=3000
    volumes: 
      - upload-files:/uploads
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
  upload-files: