version: "3"
services:
  # nginx:
  #   ports:
  #   # 3000 is port that we request on it, and when request arrives in port 3000, it will map request to port 5000 that nginx is liestining on it
  #     - "3000:5000"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
      # - /app/uploads
    environment:
      - NODE_ENV=development
      - MONGO_USER=testUser
      - MONGO_PASSWORD=mongoPassword

    command: npm run devv
  mongo:
    environment:
    # this is just for dev purpose
      - MONGO_INITDB_ROOT_USERNAME=testUser
      - MONGO_INITDB_ROOT_PASSWORD=mongoPassword